name: Deploy on Docker Publish Success

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]  # Название workflow, который нужно отслеживать
    types: 
      - completed  # Триггер при завершении workflow
    branches: 
      - main 

jobs:
  deploy:
    runs-on: self-hosted 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Stop and remove the current container
      run: |
        docker stop snake_game || true
        docker rm snake_game || true

    - name: Pull latest image of snake-game
      run: docker pull lord222/snake-game:latest

    - name: Recreate snake-game container
      run: |
        docker run -d \
          --name snake_game \
          -p 3001:80 \
          --restart always \
          lord222/snake-game:latest